spring:
  datasource:
    url: jdbc:sqlserver://aws-server-database.cbwmca88oqto.ap-southeast-2.rds.amazonaws.com:1433;databaseName=BankingSystem;encrypt=false
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: admin
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    show-sql: true

  main:
    allow-circular-references: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: example@gmail.com
    password: x88p99qxzmdvgmdu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# JWT Configuration
jwt:
  secret: your-secret-key
  expiration: 86400000 # Token expiration time in milliseconds (e.g., 24 hours)
  header: Authorization
  prefix: Bearer
